services:

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL}
    restart: unless-stopped

    volumes:
      - grafana_data:/var/lib/grafana

    networks:
      - global

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=Host(`${GRAFANA_HOSTNAME}`)"
      - "traefik.http.routers.grafana.entrypoints=https"
      - "traefik.http.routers.grafana.tls.certresolver=letsencrypt"
      - "traefik.http.services.grafana.loadbalancer.server.port=${GRAFANA_PORT}"

  prometheus:
    image: prom/prometheus:latest
    restart: unless-stopped

    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus

    networks:
      - global

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    restart: unless-stopped
    privileged: true

    devices:
      - /dev/kmsg

    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
      - /dev/disk:/dev/disk:ro

    command:
      - --housekeeping_interval=30s
      - --docker_only=true

    networks:
      - global

  node-exporter:
    image: prom/node-exporter:latest
    restart: unless-stopped

    networks:
      - global

networks:
  global:
    external: true
    name: production_network

volumes:
  grafana_data:
  prometheus_data:
